version: "3.9"

volumes:
  front_node_modules:

services:
  front:
    build: ./docker/front
    volumes:
      - ./front:/opt/app/front
      - front_node_modules:/opt/app/node_modules
    ports:
      - "35000:3000"
    command: bash -c "npm install && npm run dev"
    environment:
      - WATCHPACK_POLLING=true
    tty: true
